Uncommon Glamerweave: 1250
Helm of Underwater Action: 5000
Circlet of Human Perfection: 600
Potion of Hill Giant Strength: 250
Robe of Useful Items: 1200
Ring of Truth Telling: 1000
Bloodspear: 1300
Feywild Shard: 500
Lightbringer: 2000
Piwafwi: 5000
Shatterspike: 1500
Clockwork Amulet: 250
Cleansing Stone: 20
Shadowfell Shard: 7000
Potion of Stone Giant Strength: 2000
Ioun Stone of Historical Knowledge: 1500
Claw of the Wyrm Rune: 15000
Staff of Defense: 7000
Galder's Bubble Pipe: 6500
Wand of Entangle: 7500
War Horn of Valor: 9000
Eagle Whistle: 12000
All-Purpose Tool +1: 7000
All-Purpose Tool +2: 11000
All-Purpose Tool +3: 25000